version: '2.17.2'

services:
  app:
    container_name: app
    build: .
    depends_on:
      database:
        condition: service_healthy
    command: sh ./run-app.sh

  database:
    container_name: database
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_16_05_2024
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
